version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_backend_prod
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - ${ENV_FILE:-.env}
    restart: on-failure


# version: "3.9"

# services:
#   backend:
#     build:
#       context: .
#       dockerfile: ${DOCKERFILE}
#     container_name: node_backend
#     ports:
#       - "${PORT}:${PORT}"
#     env_file:
#       - ${ENV_FILE}
#     restart: on-failure
# docker-compose --env-file .env.dev up --build 
